# for arduino-mk
ARDUINO_DIR = /home/daniele/arduino-1.8.13
#ARDUINO_DIR = /usr/share/arduino
ARDMK_DIR = /usr/share/arduino
#AVR_TOOLS_DIR = /usr
AVR_TOOLS_DIR = /home/daniele/arduino-1.8.13/hardware/tools/avr
AVRDUDE_CONF = /etc/avrdude.conf
#ARDUINO_CORE_PATH = /usr/share/arduino/hardware/arduino/avr/cores/arduino
#ARDUINO_CORE_PATH = /usr/share/arduino/hardware/arduino/cores/arduino/
#ARDUINO_PLATFORM_LIB_PATH = /usr/share/arduino/hardware/archlinux-arduino/avr/libraries
#BOARDS_TXT = /usr/share/arduino/hardware/archlinux-arduino/avr/boards.txt
#ARDUINO_VAR_PATH = /usr/share/arduino/hardware/archlinux-arduino/avr/variants
#BOOTLOADER_PARENT = /usr/share/arduino/hardware/archlinux-arduino/avr/bootloaders


BOARD_TAG    = uno
# You’ll also need to add all libraries you’re using (both user-added and built-in) to the list of libraries like so:
# ARDUINO_LIBS += Wire \
#                SPI \
#                my_custom_lib
ARDUINO_LIBS =
USER_LIB_PATH += ../lib

include /usr/share/arduino/Arduino.mk
